backend:
  name: git-gateway
  repo: 'https://github.com/Discopigeononline/Creatip'
  branch: main
media_folder: "static/images"
public_folder: "images"
collections:

  - name: "Index"
    label: "Page d'Accueil"
    folder: "content/_index.md"
    create: false
    fields:
      - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "actu"
    identifier_field: title
    label: "Actualités"
    folder: "content/actu"
    path: "{{slug}}/"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "annuaire"
    label: "Annuaire"
    folder: "content/annuaire"
    path: "{{name}}/"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - {label: "Nom", name: "name", widget: "string"}
      - {label: "Prénom", name: "firstname", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}

  - name: "recherche"
    label: "Recherche"
    folder: "content/recherche"
    path: "{{year}}/{{month}}/{{slug}}/"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Document", name: "document", widget: "file"}

  - name: "apropos"
    label: "À Propos"
    folder: "content/apropos"
    media_folder: ""
    public_folder: ""
    create: false
    fields:
      - {label: "Contenu", name: "body", widget: "markdown"}
