backend:
  name: git-gateway
  repo: 'https://github.com/Discopigeononline/Creatip'
  branch: main
media_folder: "static/images"
public_folder: "images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Page d'Accueil"
        file: "content/_index.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}

      - name: "apropos"
        label: "À Propos"
        file: "content/apropos.md"
        fields:
          - {label: "Contenu", name: "body", widget: "markdown"}

      - name: "annuaire"
        label: "Annuaire"
        file: "content/annuaire/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - label: "Professionnels"
            name: "professionals"
            widget: "list"
            fields:
              - {label: "Nom", name: "name", widget: "string"}
              - {label: "Prénom", name: "firstname", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}

  - name: "actu"
    label: "Actualités"
    folder: "content/actu"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "recherche"
    label: "Recherche"
    folder: "content/recherche"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Document", name: "document", widget: "file"}
